# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    local: 'fr'
    avatar_directory: '%kernel.project_dir%/public/uploads/profile'
    article_picture_directory: '%kernel.project_dir%/public/uploads/articles'
    product_picture_directory: '%kernel.project_dir%/public/uploads/products'
    app.mailAddress: '%env(MAIL_ADDRESS)%'
    app.stripe_key: '%env(STRIPE_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    app.authentication_success_handler:
        class: App\Security\MonAuthenticationSuccessHandler
        arguments: ['@security.http_utils']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
